// IN/ui_sample.svelte
<script>
    // -- IMPORTS

    import { onMount } from "svelte";
    import { getApplicationData, getLanguageCodePath, getLocalizedText } from "../application.ts";

    // -- VARIABLES

    export let languageCode;

    let applicationData = getApplicationData();
    let homePageData = applicationData.homePage;
    let path = "/";

    // -- STATEMENTS
    
    onMount(
        () =>
        {
            path = window?.location?.pathname ?? "/";
        }
        );

    // -- FUNCTIONS

    function handleLanguageChange( event )
    {
        window.location.href
            = getLanguageCodePath(
                path,
                event.target.value
                );
    }
</script>

<header class="header-menu">
    <div class="header-menu-container">
        <div class="header-menu-logo">
            <h1 class="header-menu-logo-text">
                { getLocalizedText( homePageData.title ) }
            </h1>
        </div>

        <nav class="header-menu-nav">
            <ul class="header-menu-list">
                {#each applicationData.headerMenuButtonArray as menuButtonItem, buttonIndex}
                    <li class="header-menu-item">
                        <a
                            href={ `/${ languageCode }/${ menuButtonItem.route }` }
                            class="header-menu-button"
                        >
                            <span class="header-menu-button-text">
                                { getLocalizedText( menuButtonItem.text ) }
                            </span>
                        </a>
                    </li>
                {/each}
            </ul>
        </nav>

        <div class="header-menu-language">
            <select
                class="header-menu-language-select"
                value={ languageCode }
                on:change={ handleLanguageChange }
            >
                {#each Object.entries( applicationData.languageByCodeMap ) as [ code, languageItem ]}
                    <option value={ code }>
                        { getLocalizedText( languageItem.name ) }
                    </option>
                {/each}
            </select>
        </div>
    </div>
</header>

// IN/ui_sample.jsx
// -- IMPORTS

import { getApplicationData, getLanguageCodePath, getLocalizedText } from "../application.ts";

// -- FUNCTIONS

export default function HeaderMenu(
    {
        languageCode
    }
    )
{
    let applicationData = getApplicationData();
    let homePageData = applicationData.homePage;
    let path = typeof window !== "undefined" ? window.location.pathname : "/";

    return (
        <header className="header-menu">
            <div className="header-menu-container">
                <div className="header-menu-logo">
                    <h1 className="header-menu-logo-text">
                        { getLocalizedText( homePageData.title ) }
                    </h1>
                </div>
                <nav className="header-menu-nav">
                    <ul className="header-menu-list">
                        { applicationData.headerMenuButtonArray.map(
                            ( menuButtonItem, buttonIndex ) =>
                            (
                                <li key={ buttonIndex } className="header-menu-item">
                                    <a
                                        href={ `/${ languageCode }/${ menuButtonItem.route }` }
                                        className="header-menu-button"
                                    >
                                        <span className="header-menu-button-text">
                                            { getLocalizedText( menuButtonItem.text ) }
                                        </span>
                                    </a>
                                </li>
                            )
                            )}
                    </ul>
                </nav>
                <div className="header-menu-language">
                    <select
                        className="header-menu-language-select"
                        value={ languageCode }
                        onChange={
                            ( event ) =>
                                window.location.href
                                    = getLanguageCodePath(
                                        path,
                                        event.target.value
                                        )
                            }
                    >
                        { Object.entries( applicationData.languageByCodeMap ).map(
                            ( [ languageCode, languageItem ] ) =>
                            (
                                <option key={ languageCode } value={ languageCode }>
                                    { getLocalizedText( languageItem.name ) }
                                </option>
                            )
                            )}
                    </select>
                </div>
            </div>
        </header>
        );
}
